### ISSUE TITLE
There is again issue #24 "CiviCRM Contribution could not be created"

### ISSUE THREAD

**Issue by alexletizia** [mecachisenros/woocommerce_civicrm#38]
After the latest updates the plugin no longer works correctly:

(SOLVED) 1. the Woocommerce Civim tab does not appear and "replicates" the contact area as you see here:

![Woocommerce Civicrm issue - WP 5 33 2 and Woo 4 9 2](https://user-images.githubusercontent.com/40597363/106382617-0d6cbc80-63c1-11eb-9faf-ba796fd59bff.jpg)

2. the same problem as "issue # 24" occurs again ("CiviCRM Contribution could not be created" in order note, both with PayPAL and with deferred payment) but contact is correctly created.

Our configuration:

CiviCRM 5.33.2
Woocommerce CiviCRM 2.3
CiviCRM Admin Utilities 0.8.2
Woocommerce 4.9.2
Wordpress 5.6 (with or without JQuery Migrate plugin fixes)
PHP 7.3.19

**Comment by christianwach** [comment]
@alexletizia Try clearing the CiviCRM caches. There is an easy-to-find option to do so in the CiviCRM Admin Utilities settings.

**Comment by alexletizia** [comment]
> @alexletizia Try clearing the CiviCRM caches. There is an easy-to-find option to do so in the CiviCRM Admin Utilities settings.

Thx, but cleaning cache (also on Cloudflare) solve only the "replication" of the contact area in Woocommerce orders tab.

"CiviCRM Contribution could not be created" is still an issue.

**Comment by mecachisenros** [comment]
@alexletizia please test latest master branch.

**Comment by alexletizia** [comment]
i'm sorry @mecachisenros but it still doesn't work: the order is displayed correctly in the "Woocomerce order" tab but the contribution on CiviCRM is not created.

However, the message "the contribution may not be created" is no longer displayed in the Woocommerce notes.

The process is: from "pending order" (for pending payment)> to "complete", but the contribution is not created even if the payment is completed immediately via PayPAL.

Note: we have also upgraded to:

- **CiviCRM 5.34**
- Woocommerce CiviCRM 2.3
- CiviCRM Admin Utilities 0.8.2
- Woocommerce 4.9.2
- **Wordpress 5.6.1** (with or without JQuery Migrate plugin fixes)
- PHP 7.3.19
- **even without any additional Woocommerce plugins installed**
- **even without any additional CiviCRM extentions installed**

**Comment by mecachisenros** [comment]
@alexletizia just pushed a couple small fixes, can you test again

**Comment by alexletizia** [comment]
:(    I'm sorry @mecachisenros but it still doesn't work.

- I have dowloaded the last .zip file and I have reinstalled it after cleaning cache at every level (also on Cloudflare): a new contact is created (or an exsiting contact is upgraded) but the relative contribution doesnt' created.
- Could it be useful to clean something on MySQL?
- Note that **Woocommerce was just upgraded at the 5.0** ver.

Thank you for your effort.

- - - 
CiviCRM 5.34
Woocommerce CiviCRM 2.3 (**fix**)
CiviCRM Admin Utilities 0.8.2
**Woocommerce 5.0**
Wordpress 5.6.1 (with or without JQuery Migrate plugin fixes)
PHP 7.3.19
even without any additional Woocommerce plugins installed
even without any additional CiviCRM extentions installed

**Comment by JoeMurray** [comment]
We have noticed this on a site we are developing. Edsel has got it working on our site and will submit a PR tomorrow.

**Comment by alexletizia** [comment]
Hi @JoeMurray , have you solved the problem? to submit a PR?

Thank you for your effort.

**Comment by netzih** [comment]
Has this been fixed?
I am noticing this on a site I use.

**Comment by mecachisenros** [comment]
@netzih @alexletizia can you test again with latest branch? 

There was a case where if no `camping_id` was set on the contribution nor the settings page the contribution would not be created.

**Comment by alexletizia** [comment]
> @netzih @alexletizia can you test again with latest branch?
> 
> There was a case where if no `camping_id` was set on the contribution nor the settings page the contribution would not be created.

YEESSS! It works!     Thx a lot.

**Comment by netzih** [comment]
> @netzih @alexletizia can you test again with latest branch?
> 
> There was a case where if no `camping_id` was set on the contribution nor the settings page the contribution would not be created.

Thanks,

I updated it, will see when the next order comes in.

I did test it with an order and payment method was cash on delivery but the order did not come up in the contributions tab, 
I am wondering if it's intended to only come up with completed payments (by CC and not cash on delivery orders) but the order is set as completed so I would imagine it is supposed to come up in the contributions tab and still did not.

**Comment by alexletizia** [comment]
@netzih We tested with a bank transfer order; the contribution was correctly "pending" on CiviCRM until the order was completed on Woocommerce; then also on CiviCRM it became "completed".

**Comment by netzih** [comment]
> @netzih We tested with a bank transfer order; the contribution was correctly "pending" on CiviCRM until the order was completed on Woocommerce; then also on CiviCRM it became "completed".

I don't know.
I updated the plugin to master and an order came in 2 hours ago, I can see the order in the woocommerce tab on the contact but it's not coming up under contributions...

**Comment by netzih** [comment]
When looking at my logs I am seeing 
```Mar 14 11:58:10  [error] 
$Fatal Error Details = array:3 [
  "message" => "You do not have permission to access this page."
  "code" => null
  "exception" => CRM_Core_Exception {#11668
    -errorData: array:1 [
      "error_code" => 0
    ]
    #cause: null
    -_trace: null
    #message: "You do not have permission to access this page."
    #code: 0
    #file: "/sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Utils/System/WordPress.php"
    #line: 505
    trace: {
      /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Utils/System/WordPress.php:505 {
        › public function permissionDenied() {
        ›   throw new CRM_Core_Exception(ts('You do not have permission to access this page.'));
        › }
      }
      **/sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Utils/System.php:60** { …}
      /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Event/Page/EventInfo.php:65 { …}
      /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:312 { …}
     / sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:68 { …}
      /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm.php:1644 { …}
      /sitedir/httpdocs/wp-content/plugins/civicrm/includes/civicrm.basepage.php:352 { …}
      /sitedir/httpdocs/wp-includes/class-wp-hook.php:287 { …}
      /sitedir/httpdocs/wp-includes/class-wp-hook.php:311 { …}
      /sitedir/httpdocs/wp-includes/plugin.php:551 { …}
      /sitedir/httpdocs/wp-includes/class-wp.php:758 { …}
      /sitedir/httpdocs/wp-includes/functions.php:1291 { …}
      /sitedir/httpdocs/wp-blog-header.php:16 { …}
      /sitedir/httpdocs/index.php:17 { …}
    }
  }
]


Mar 14 11:58:10  [debug] $backTrace = #0 /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(433): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(CRM_Core_Exception))
#2 /sitedir/httpdocs/wp-content/plugins/civicrm/civicrm.php(1644): CRM_Core_Invoke::invoke((Array:3))
#3 /sitedir/httpdocs/wp-content/plugins/civicrm/includes/civicrm.basepage.php(352): CiviCRM_For_WordPress->invoke()
#4 /sitedir/httpdocs/wp-includes/class-wp-hook.php(287): CiviCRM_For_WordPress_Basepage->basepage_handler(Object(WP))
#5 /sitedir/httpdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, (Array:1))
#6 /sitedir/httpdocs/wp-includes/plugin.php(551): WP_Hook->do_action((Array:1))
#7 /sitedir/httpdocs/wp-includes/class-wp.php(758): do_action_ref_array("wp", (Array:1))
#8 /sitedir/httpdocs/wp-includes/functions.php(1291): WP->main("")
#9 /sitedir/httpdocs/wp-blog-header.php(16): wp()
#10 /sitedir/httpdocs/index.php(17): require("/sitedir/httpdocs/wp-blog-header.php")
#11 {main}


Mar 14 18:58:45  [info] Not able to find contribution

Mar 14 18:58:45  [info] Not able to find contribution

Mar 14 18:58:46  [info] $Geocoding failed. Message from Google: (REQUEST_DENIED) = You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

Mar 14 18:58:46  [info] Expected one UFMatch but found 0

Mar 14 18:58:46  [info] $Geocoding failed. Message from Google: (REQUEST_DENIED) = You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

Mar 14 18:58:46  [info] Expected one UFMatch but found 0

Mar 14 18:58:46  [info] Not able to find contribution

Mar 14 18:58:46  [info] Not able to add contribution

Mar 14 18:58:46  [info] One of parameters  (value: ) is not of the type Integer

Mar 14 18:58:49  [info] Not able to find contribution

Mar 14 18:58:51  [info] Not able to find contribution
